image: r-base

variables:
  QUARTO_VERSION: 0.9.522
  BASENAME: index # name of main .qmd file

before_script:
  - apt-get update -qq && apt-get install -y -qq libssl-dev libcurl4-openssl-dev libudunits2-dev git pandoc pandoc-citeproc 

pages:
  script:
    - rm -r _site/*
    - wget "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"
    - dpkg -i quarto-${QUARTO_VERSION}-linux-amd64.deb
    - R -e "install.packages('quarto',repos='https://packagemanager.rstudio.com/all/__linux__/focal/latest')"
    - R -e "install.packages('leaflet',repos='https://cran.us.r-project.org')"
    - quarto render
    - cp -R _site/ public/
  artifacts:
    paths:
      - public
  only:
    - main
